# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.5.1-13-g4938979
_src_path: gh:algorandfoundation/algokit-puya-template
author_email: altynbek.orumbayev@makerx.com.au
author_name: Altynbek Orumbayev
contract_name: hello_world
deployment_language: python
preset_name: production
project_name: test-contracts

