# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.10.1-9-gc156ed7
_src_path: gh:algorandfoundation/algokit-react-frontend-template
author_email: altynbek.orumbayev@makerx.com.au
author_name: Altynbek Orumbayev
cloud_provider: vercel
preset_name: production
project_name: test-frontend

