name: Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '.vscode/**'
      - '.idea/**'

permissions:
  contents: read
  packages: read

jobs:
  test-frontend-release:
    name: Run test-frontend release
    secrets: inherit
    uses: ./.github/workflows/test-frontend-cd.yaml
