name: Release test-frontend

on:
  workflow_call:

permissions:
  contents: read
  packages: read

jobs:

  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Vercel
    environment: frontend-prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "poetry"

      - name: Install algokitt
        run: pipx install git+https://github.com/algorandfoundation/algokit-cli@feat/orchestration-linking

      - name: Bootstrap dependencies
        run: algokit bootstrap all --project-name 'test-frontend'

      # Set your vercel project env variables on your github repository (see README for more info)
      - name: Publish to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: algokit -v project run ci-deploy-vercel --project-name 'test-frontend'

