name: Release test-frontend

on:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "**.md"
      - ".vscode/**"
      - ".idea/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: false

permissions:
  contents: read
  packages: read

jobs:
  validate:
    name: Validate frontend(s)
    uses: ./.github/workflows/frontend-ci.yaml

  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Vercel
    environment: frontend-prod
    needs:
      - validate
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "poetry"

      - name: Install algokitt
        run: pipx install git+https://github.com/algorandfoundation/algokit-cli@feat/orchestration-linking

      - name: Bootstrap dependencies
        run: algokit bootstrap all --project-name 'test-frontend'

      # Set your vercel project env variables on your github repository (see README for more info)
      - name: Publish to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: algokit project run deploy-vercel --project-name 'test-frontend'
