name: Pull Request validation

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

extends:
  template: .github/workflows/validate-contracts-template.yml

jobs:
  pool:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
