name: Pull Request validation

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

extends:
  - .github/workflows/validate-contracts-template.yml
