name: Pull Request validation

on: [pull_request]


jobs:
  test-contracts-ci:
    name: Run test-contracts validation
    uses: ./.github/workflows/test-contracts-ci.yaml

  test-frontend-ci:
    name: Run test-frontend validation
    uses: ./.github/workflows/test-frontend-ci.yaml

